name: Semantic release

on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      # Prepare for release
      - name: Install dependencies
        run: npm install

      - name: Run typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build
      # Update changelog
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      # NPM
      - name: Publish to NPM
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # GitHub Packages
      - name: Publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          registry-url: "https://npm.pkg.github.com"
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
