name: Semantic release

on: workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org"
      - name: Install dependencies
        run: npm install
      - name: Run typecheck
        run: npm run typecheck
      - name: Build
        run: npm run build
      - name: Semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
